### ISSUE TITLE
[Feature Request] Add Edit button

### ISSUE THREAD

**Issue by Pillowg1rl** [jango/site-alert#3]
Hi there,

I love your plugin and I use it for reminding me to work things :)
It would be awesome if there was an "edit" button on the option-page to edit certin reminders instead of going into the Source code, copy the text and url, delete it and add it new.
Would that be possible ? :)

Thanks
~Michelle

**Comment by jango** [comment]
Thank you for the feedback. Had to redo the entire options page but now there is an edit button :)
